services:
  backend:
    build: .
    container_name: eventsync-backend
    ports:
      - "8080:8080"

  frontend:
    build: ./frontend
    container_name: eventsync-frontend
    environment:
      - REACT_APP_API_URL=http://localhost:8080
    ports:
      - "3000:3000"
    depends_on:
      - backend